module ContractsHelper
  SalesrepOption = [
  "Achten, David J",
  "Allen, Mr. Harry",
  "Anderson, Chris",
  "Anselm, Michael Scott",
  "Baas, Christopher T",
  "Baldwin Jr, Robert R",
  "Barnes, Dean",
  "Bishop, Joe",
  "Bonneau, Mr. Robert",
  "Brongel, Edward",
  "Cappello, Daniel",
  "Clifton, Josh",
  "Coleman, Mary Susan",
  "Colley, Terry L",
  "Cooper, Tim",
  "Cox, Michael",
  "Dabbas, Sami",
  "Dean, Mr. Devesha",
  "Denk, Mr. Nathan",
  "Dharani, Zulfiquarali M",
  "Dill, Jason B",
  "Dobry, Robert J",
  "Edwards, Tara A",
  "Farmer, William M",
  "Gagliardo, Catherine",
  "Hackerott, Aaron S",
  "Hartnett, George",
  "Hoffman, Mr. Mark",
  "Horning, David Todd",
  "House Alta Fuels",
  "House Carter",
  "House Lakeside",
  "House Texor",
  "Huber, Gerald A",
  "Hudson-Miltenberger, Jason M",
  "Hurley, Annette",
  "James, Aaron T",
  "Janson, Michelle",
  "Kaegebein, Erin E",
  "Kalis, Brian D",
  "Kilpatrick, Ms. Beth A",
  "Kisch, Mr. Kevin",
  "Kittrell, Michael W",
  "Kraft, Paul",
  "Latcham, Ronnie L",
  "Lee, Robert E",
  "Livermore, Lewis C",
  "Ludwig, Mr. Michael",
  "Ludwig, Paul",
  "Luehmann, Mark",
  "Lundquist, Michael",
  "Maes, Lucas",
  "Mannion, John",
  "Marable, Mrs. Shelly",
  "McCoy, Loresa K",
  "McGill, Eric D",
  "McKelvey, Mr. William P.",
  "McLemore, Ms. Traci",
  "McLeod, Garth",
  "McNally, Mr. Robert J",
  "Mercil, Miss Colleen",
  "Milligan, David J",
  "Milligan, Michael J",
  "Milligan, Tyler Jon",
  "Monty, Mr. Chad M",
  "Mortensen, Chad R",
  "Mullins, Joel",
  "Nelson, Kurt E",
  "Nigro, Austin J",
  "Oesterreich, Mr. Paul E",
  "Ohara, Mr. Dennis",
  "Penrod, Robert M",
  "Pittala, Lenny",
  "Powers, Mark",
  "Prosser, James S",
  "Rand, Scott",
  "Reilly, Mr. Stuart P",
  "Rodrigues, Michael A",
  "Rogers, Steven",
  "Sammons, James L",
  "Schroeder, Binny",
  "Shepherd, Tyler",
  "Shireman, Mr. William H",
  "Singh, Akash",
  "Smith, Aaron",
  "Sobczak, Mr. John",
  "Speropulos, George",
  "St Martin, Mr. Jason",
  "Steoger, Mr. Samuel D. (Sam)",
  "Stergiou, Stefanos",
  "Tappan, Jayme L",
  "Thomas, James V",
  "Thomas, Raymond E",
  "Whelan, Mr. Casey D"
  ]
  
end