module ContractsHelper
  SalesrepOption = [
    "Aaron Smith",
    "Akash Singh",
    "Annette Hurley",
    "Austin Nigro",
    "Beth Kilpatrick",
    "Binny Schroeder",
    "Cate Gagliardo",
    "Chad Monty",
    "Colleen Mercil",
    "Dale Robinett",
    "Dave Achten",
    "Dave Milligan",
    "Edward Brongel",
    "Eric McGill",
    "George Arnold",
    "George Hartnett",
    "George Speropulos",
    "Gerald Huber",
    "Jason Dill",
    "Jason Miltenberger",
    "Jayme Tappan",
    "Joe Bishop",
    "Joel Mullins",
    "John Trammell",
    "Lewis Livermore",
    "Mark Hoffman",
    "Michelle Janson",
    "Mike Kittrell",
    "Nathan Denk",
    "Paul Kraft",
    "Rob Baldwin",
    "Robert Dobry",
    "Shelly Marable",
    "Steve Rogers",
    "Stuart Reilly",
    "Susie Coleman",
    "Tara Edwards",
    "Terry Colley",
    "Tyler Milligan",
    "Tyler Shepherd",
  ]
  
end