module LinesHelper
    IndexOption = [
        ["Argus",[
        "Argus Diesel ULSD Chicago pipe fob cycle 1 - Houston close",
        "Argus Diesel ULSD Chicago pipe fob cycle 2 - Houston close",
        "Argus Diesel ULSD Colonial 62 pipe fob cycle 1 - Houston close",
        "Argus Diesel ULSD Group 3 Magellan X pipe fob prompt Prmpt - Houston close",
        "Argus Diesel ULSD NYH barge fob prompt Prmpt - Houston close",
        "Argus Distillates line space Colonial Line02 cycle 1 - Houston close",
        "Argus Ethanol Chicago Argo in-tank transfer month 1 - Houston close",
        "Argus Fuel oil bunker 380 cst Los Angeles Prmpt - Houston close",
        "Argus Gasoline 87 conv Chicago pipe fob cycle 1 - Houston close",
        "Argus Gasoline 87 conv Colonial M pipe fob lowest RVP wtd avg cycle 1 - Houston close",
        "Argus Gasoline 89 conv Chicago pipe fob cycle Prmpt - Houston close",
        "Argus Gasoline 91 conv Chicago pipe fob cycle 1 - Houston close",
        "Argus Gasoline 91 conv Group 3 Magellan A pipe fob Prmpt - Houston close",
        "Argus Gasoline 93 conv Colonial V pipe fob lowest RVP cycle 1 - Houston close",
        "Argus Gasoline 93 conv USGC waterborne fob lowest RVP Prmpt - Houston close",
        "Argus Gasoline line space Colonial Line01 cycle 1 - Houston close",
        "Argus Gasoline prem CBOB Colonial D pipe fob lowest RVP cycle 1 - Houston close",
        "Argus Gasoline prem CBOB NYH barge fob prompt continuous Prmpt - Houston close",
        "Argus Gasoline prem RBOB Chicago pipe fob cycle 1 - Houston close",
        "Argus Gasoline prem RBOB Colonial H pipe fob cycle 1 - Houston close",
        "Argus Gasoline prem RBOB NYH barge fob prompt continuous Prmpt - Houston close",
        "Argus Gasoline reg CBOB Chicago pipe fob cycle 1 - Houston close",
        "Argus Gasoline reg CBOB Colonial A pipe fob lowest RVP cycle 1 - Houston close",
        "Argus Gasoline reg CBOB NYH barge fob lowest RVP not 7.8 or 7.0 prompt Prmpt - Houston close",
        "Argus Gasoline reg RBOB Chicago pipe fob cycle 1 - Houston close",
        "Argus Gasoline reg RBOB Colonial F pipe fob cycle 1 - Houston close",
        "Argus Gasoline reg RBOB Colonial F pipe fob cycle 2 - Houston close",
        "Argus Gasoline reg RBOB NYH barge fob prompt continuous Prmpt - Houston close",
        "Argus Heating oil NYH barge fob prompt Prmpt - Houston close"]],
        ["NYMEX",[
        "NYM ULSD NY HARBOR #2 (PIT) - Month (2nd Month)",
        "NYM ULSD NY HARBOR #2 (PIT) - Month (Front Month)",
        "NYMEX Light Sweet Crude Oil (WTI) Futures Electronic (Front Month)",
        "NYMEX Light Sweet Crude Oil (WTI) Futures Pit (Front Month)",
        "NYMEX NY Harbor ULSD Futures Pit",
        "NYMEX NY Harbor ULSD Futures Pit (2nd Month)",
        "NYMEX RBOB Gasoline Financial Futures Electronic (Front Month)",
        "NYMEX RBOB Gasoline Futures Electronic (Front Month)",
        "NYMEX RBOB Gasoline Futures Pit (2nd Month)",
        "NYMEX RBOB Gasoline Futures Pit (Front Month)"]],
        ["Platts",[
        "Platts DTN ULSD Regina SK RkAvg",
        "Platts DTN ULSD Regina SK UnbAvg",
        "Platts Ethanol Chicago Pipe",
        "Platts Ethanol FOB Houston Barge",
        "Platts Ethanol NYH Barge Mo01",
        # "Platts Ethanol RIN Cal Yr02",
        "Platts Gasoil No.2 New York Harbor Barge",
        "Platts Gasoil No.2 USGC Prompt Pipeline",
        "Platts Gasoline CARBOB San Francisco CA Pipeline",
        "Platts Gasoline CBOB 87 USGC Houston Prompt Pipeline",
        "Platts Gasoline CBOB 87 USGC Waterborne",
        "Platts Gasoline CBOB 93 USGC Houston Prompt Pipeline",
        "Platts Gasoline CBOB Chicago Pipe",
        "Platts Gasoline CBOB NY Barge",
        "Platts Gasoline PBOB Chicago Pipe",
        "Platts Gasoline Prem RBOB NY Barge",
        "Platts Gasoline Prem Unl 91 Group 3 Pipeline",
        "Platts Gasoline Prem Unleaded 91 Chicago Pipe",
        "Platts Gasoline RBOB 83.7 USGC Houston prompt pipeline",
        "Platts Gasoline RBOB 91.4 USGC Houston Prompt Pipeline",
        "Platts Gasoline RBOB Chicago Pipe",
        "Platts Gasoline RBOB NY Barge",
        "Platts Gasoline RBOB NY Cargo",
        "Platts Gasoline Reg Unl San Francisco CA Pipeline",
        "Platts Gasoline Unl 87 NY Barge",
        "Platts Gasoline Unl 87 USGC Prompt Pipeline",
        "Platts Gasoline Unl 93 NY Barge",
        "Platts Gasoline Unl 93 USGC Prompt Pipeline",
        "Platts Gasoline Unl Sub Octane Group 3 Pipeline",
        "Platts Gasoline Unleaded 87 Chicago Pipe",
        "Platts Gasoline Unleaded 89 Chicago Pipe",
        "Platts Jet Kero 54 USGC Prompt Pipeline",
        "Platts Jet Kero Group 3 Pipeline",
        "Platts Jet Kero ULS No1 FOB Chicago Pipe",
        "Platts NYMEX NY ULSD 01-Mo Floor",
        "Platts NYMEX NY ULSD at Houston MOC Mo01",
        "Platts NYMEX NY ULSD at Houston MOC Mo02",
        "Platts NYMEX RBOB 01-Mo Floor",
        "Platts NYMEX RBOB at Houston MOC Mo01",
        "Platts NYMEX RBOB at Houston MOC Mo02",
        "Platts ULS Heating Oil USGC Prompt Pipeline",
        "Platts ULSD (EPA) Portland OR Pipeline",
        "Platts ULSD FOB Chicago Pipe",
        "Platts ULSD Group 3 Pipeline",
        "Platts ULSD New York Harbor Barge",
        "Platts ULSD No2 CARB Diesel San Francisco CA Pipeline",
        "Platts ULSD USGC Prompt Pipeline",
        "Platts ULSD USGC Waterborne"]]
        ]
end
